name: Publish Unity Package
on: 
  push:
    branches:
      - master
jobs:
  # All we need to do is to make Packages/AssetLock the project root (remove all other files)
  re-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: master
          
      - name: Move
        # remove all folders and files except for ./Packages to start
        run: |
          shopt -s extglob
          rm -rf !(Packages)
          mv Packages/AssetLock/* .
          rm -rf Packages
        
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Re-root project to Packages/AssetLock'
          
      - name: Push changes
        run: git push origin HEAD:package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}